export { default as NavBar } from "./NavBar";
export { default as Homepage } from "./Homepage";
export { default as Cryptocurrencies } from "./Cryptocurrencies";
export { default as CryptoDetails } from "./Cryptodetails";
export { default as Exchanges } from "./Exchanges";
// export { default as News } from "./News";
// export { default as NavBar } from "./NavBar";
// export { default as NavBar } from "./NavBar";
// export { default as NavBar } from "./NavBar";
// export { default as NavBar } from "./NavBar";
// export { default as NavBar } from "./NavBar";
